### ISSUE TITLE
eslint-config-angular support

### ISSUE THREAD

**Issue by healthypets** [zaggino/brackets-eslint#47] opened 2016-09-19 16:11 UTC
Is it possible to get this working with eslint-config-angular?

I have been having issues with it not finding the module, even though I have tried both global and local installations.

Thanks!

**Comment by zaggino** [comment] 2016-09-19 19:02
Can you provide a link to your project on github?
Or create a sample one if you don't have it.
Thanks

**Comment by healthypets** [comment] 2016-09-19 20:01
https://github.com/healthypets/project-base

Wasn't sure if you wanted the node modules or not so I intentionally left them. Can do a clean install if necessary. ESLint in brackets throws a 'cannot find module eslint-config-angular' error when trying to lint inside of brackets for lint-test.js

**Comment by zaggino** [comment] 2016-09-19 20:25
So, your project is using `eslint-config-angular` but the error message says this:

![image](https://cloud.githubusercontent.com/assets/1067319/18647754/e05da894-7efa-11e6-8650-d91bc7b3630c.png)

You can fix it by doing `npm install --save eslint-plugin-angular` in your project. After that:

![image](https://cloud.githubusercontent.com/assets/1067319/18647781/fe24289e-7efa-11e6-9c3e-433128d8cf9f.png)

**Comment by healthypets** [comment] 2016-09-19 21:03
Hmm perhaps there is a difference in environment here then.

Mine is showing:

```
ESLint terminated with error: Error: Cannot find module 'eslint-config-angular' Referenced from: C:\xampp\htdocs\project-base\.eslintrc.js	
```

I'm on Windows, though that's likely not the only env difference.

**Comment by zaggino** [comment] 2016-09-19 21:18
What version of Brackets are you running?

**Comment by zaggino** [comment] 2016-09-19 21:19
I recommend trying out latest 1.8 pre-release from here: https://github.com/adobe/brackets/releases or my electron build from here: https://github.com/zaggino/brackets-electron/releases

Brackets before 1.8 doesn't work with eslint version 3

**Comment by healthypets** [comment] 2016-09-19 21:21
Currently running Release 1.7 so that would make sense. I'll install that release. Apparently I missed that memo, thanks!

**Comment by zaggino** [comment] 2016-09-19 21:26
https://github.com/zaggino/brackets-eslint/issues/36

**Comment by zaggino** [comment] 2016-09-19 21:26
Let me know if the upgrade to 1.8 did work for you please.

**Comment by healthypets** [comment] 2016-09-19 21:38
Updated the to latest 1.8 pre-release from Brackets. Still getting the following:

```
ESLint terminated with error: Error: Cannot find module 'eslint-config-angular' Referenced from: C:\xampp\htdocs\project-base\.eslintrc.js
```

If I just have base rules in the .eslintrc.js then it seems to function fine. It just can't seem to find the module when I use: "extends": "angular"

**Comment by zaggino** [comment] 2016-09-19 21:45
When you open brackets console (Debug > Show developer tools or F12), do you have anything else there?

**Comment by healthypets** [comment] 2016-09-19 21:52
```
NodeDebugUtils.js:111 [node-error 2:47:18 PM] [brackets-eslint] Error thrown in executeOnText: Error: Cannot find module 'eslint-config-angular'
Referenced from: C:\xampp\htdocs\project-base\.eslintrc.js
    at Object.ModuleResolver.resolve (C:\Users\User\AppData\Roaming\Brackets\extensions\user\brackets-eslint\node_modules\eslint\lib\util\module-resolver.js:75:19)
    at resolve (C:\Users\User\AppData\Roaming\Brackets\extensions\user\brackets-eslint\node_modules\eslint\lib\config\config-file.js:479:33)
    at load (C:\Users\User\AppData\Roaming\Brackets\extensions\user\brackets-eslint\node_modules\eslint\lib\config\config-file.js:496:24)
    at C:\Users\User\AppData\Roaming\Brackets\extensions\user\brackets-eslint\node_modules\eslint\lib\config\config-file.js:392:36
    at Array.reduceRight (native)
    at applyExtends (C:\Users\User\AppData\Roaming\Brackets\extensions\user\brackets-eslint\node_modules\eslint\lib\config\config-file.js:363:28)
    at Object.load (C:\Users\User\AppData\Roaming\Brackets\extensions\user\brackets-eslint\node_modules\eslint\lib\config\config-file.js:530:22)
    at loadConfig (C:\Users\User\AppData\Roaming\Brackets\extensions\user\brackets-eslint\node_modules\eslint\lib\config.js:64:33)
    at getLocalConfig (C:\Users\User\AppData\Roaming\Brackets\extensions\user\brackets-eslint\node_modules\eslint\lib\config.js:126:23)
    at Config.getConfig (C:\Users\User\AppData\Roaming\Brackets\extensions\user\brackets-eslint\node_modules\eslint\lib\config.js:227:22)
    at processText (C:\Users\User\AppData\Roaming\Brackets\extensions\user\brackets-eslint\node_modules\eslint\lib\cli-engine.js:223:27)
    at CLIEngine.executeOnText (C:\Users\User\AppData\Roaming\Brackets\extensions\user\brackets-eslint\node_modules\eslint\lib\cli-engine.js:761:26)
    at C:\Users\User\AppData\Roaming\Brackets\extensions\user\brackets-eslint\dist\node\eslint.js:238:23
    at fs.js:266:14
    at C:\xampp\htdocs\project-base\node_modules\graceful-fs\graceful-fs.js:43:10
    at C:\Program Files (x86)\Brackets\www\extensibility\node\node_modules\fs-extra\node_modules\rimraf\node_modules\graceful-fs\graceful-fs.js:103:5
```

**Comment by zaggino** [comment] 2016-09-19 23:24
I have now tried on second windows machine with your project and `npm install eslint-plugin-angular` fixes it again. Can't help here. (I'm using brackets-electron for windows on both but that should not make a difference)

**Comment by healthypets** [comment] 2016-09-20 00:52
Okay, I will look at setting this up on a clean virtual machine. An acquaintance tried this as well and had the same issue not being able to find the config module. Perhaps a clean env will be different.

Thanks for your time!

**Comment by zaggino** [comment] 2016-09-20 01:01
I'd be interesting to find out what the problem is. If you wan't me to provide any settings, installed apps or whatever from my windows machines, let me know. But they are quite normal, latest versions of node, npm, git, etc.

**Comment by zaggino** [comment] 2016-09-20 01:02
Please also be sure to test this with https://github.com/zaggino/brackets-electron/releases too when you're at it, thanks!

**Comment by zaggino** [comment] 2016-09-20 03:00
I've also released `brackets-eslint@3.0.0` which includes a fair bit of refactoring, maybe that'll help too.

**Comment by guess-and-correct** [comment] 2016-09-20 18:37
Updated Brackets to 1.8 and now ESLint doesn't work at all. 
It worked just fine with 1.7, but now there's no coming back.

`ESLintError: Legacy node process detected, please update to Brackets 1.8 or Brackets-Electron`

**Comment by zaggino** [comment] 2016-09-20 21:13
Did you install Brackets 1.8 from here? https://github.com/adobe/brackets/releases

**Comment by zaggino** [comment] 2016-09-20 21:24
@guess-and-correct `3.0.2` will fix it but you need to use `eslint` 2.x in your project

**Comment by guess-and-correct** [comment] 2016-09-21 16:56
@zaggino I did (the `.msi` package). 
For what it's worth, when updating ESLint using npm-registry, it threw a couple warnings about npm being too old. Even after updating Brackets to `1.8`, npm-registry is still using `node v0.10.24` and `npm 2.14.5`.

**Comment by zaggino** [comment] 2016-11-21 00:48
This is now fixed with latest Brackets (includes node v6)

**Closed by zaggino** 2016-11-21 00:48 UTC
Labels: waiting for user
